### ISSUE TITLE
Ninja: build stopped: subcommand failed

### ISSUE THREAD

**Issue by juan-tellez** [guisalmon/pocse#1]
Hi! I was trying out your tool and I get an error after I have edited the theme and the CSS is being generated. I used this command `./pop_customization.sh -c -e -i -o Custom2` and then used hex color values during the prompts. Should I do something differently?
![Screenshot from 2019-12-03 14-15-27](https://user-images.githubusercontent.com/46802370/70077925-2371c800-15d8-11ea-8202-2fd1931c9170.png)
This is my system:
![Screenshot from 2019-12-03 14-20-45](https://user-images.githubusercontent.com/46802370/70078143-8c594000-15d8-11ea-9d18-02166706f7f3.png)

Thanks in advance!

**Comment by guisalmon** [comment]
Hum... Taking a look. My guess is that for some reason a color wasn't written properly in one of the scss files for the gtk theme. Can you copy/paste the content of the Pop-Custom2_colors file in pocse/color_exports to this thread please ?

**Comment by juan-tellez** [comment]
Hmm, I don't seem to have a `color_exports` dir, unless I'm looking in the wrong place?
![Screenshot from 2019-12-03 14-40-09](https://user-images.githubusercontent.com/46802370/70079377-025ea680-15db-11ea-9edd-37180575013d.png)

**Comment by guisalmon** [comment]
You're definitely looking in the right place.
Something wrong with my work, I'll fix this and then you can try again.
As a quick fix for your theme, go to /pocse/Pop-Custom2/gtk/src/light/gtk-3.20 and in _tweak.scss line 531 replace 
`$_close_button_color: mix(, #E56A54, 50%);`
with 
`$_close_button_color: mix(#FFAD00, #E56A54, 50%);`
(you can put whatever hex code you used instead of the bright orange in place of #FFAD00)

**Comment by guisalmon** [comment]
Then 
```
meson build && cd build
ninja
ninja install
```
from inside the Pop-Custom2 directory

**Comment by guisalmon** [comment]
Not sure this will fix the entire issue, but at least if you have the same problem again, you'll be able to provide me with Pop-Custom2_colors and I'll be able to reproduce.
`git pull` from your posce directory will update your script.

**Comment by juan-tellez** [comment]
I did a git pull and this is what I got for the colors:
```
Gnome
Color               Light  Dark     Neutral
$orange             .      #AD154F  .
$highlights_orange  .      #A0252B  .
$text_orange        .      #FFD7A1  .
$blue               .      #6ACAD8  .
$highlights_blue    .      #63B1BC  .
$text_blue          .      #94EBEB  .
$base_color         .      #151515  .
$bg_color           .      #2B2B2B  .
$selected_bg_color  .      #94EBEB  .
$gdm_grey           .      .        #2B2B2B
GTK
Color               Light    Dark     Neutral
$orange             .        #AD154F  .
$highlights_orange  .        #A0252B  .
$text_orange        .        #FFD7A1  .
$blue               .        #6ACAD8  .
$highlights_blue    .        #63B1BC  .
$text_blue          .        #94EBEB  .
$base_color         .        #151515  .
$bg_color           .        #2B2B2B  .
$headerbar_color    #2B2B2B  #2B2B2B  .
$selected_bg_color  .        #94EBEB  .
```
This was my output after editing the colors if it helps:
![Screenshot from 2019-12-03 15-37-27](https://user-images.githubusercontent.com/46802370/70083715-553c5c00-15e3-11ea-8f38-3ef7d4f3214b.png)

**Comment by guisalmon** [comment]
Thanks! I think I know what the issue is, I'm fixing it.

**Comment by guisalmon** [comment]
Reproduced and fixed.
Update the script and your side and run
```
./pop_customization.sh -c -e -i -s color_exports/Pop-Custom2_colors -o Custom3
```
